Add files via upload
stuvusIT/sympa pull request #1
Opened 2017-09-27 17:20 UTC by AznFreak

2017-09-28 09:02 UTC, SlothOfAnarchy requested changes

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/configure.yml
> +- name: Defines which parameters/files are editable by owners
The task names specify what is being done in a task, like `Template edit_list configuration`.
The same thing with the other task names.

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/configure.yml
> +	src: sympa.conf.j2
Please indent using spaces.

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/configure.yml
> +- name: Virtual Host definition for Sympairtual Host definition for Sympa
You pasted the name twice :D

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/configure.yml
> +  dest: /usr/share/doc/sympa/examples/sample/
Is this file really used in a sample folder?

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/install.yml
> +  notify: restart sympa
where is the handler?

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/main.yaml
> +- include: install.yml
`include` is deprecated. Use `include_tasks` or `import_tasks`

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/install.yml
> +    owner: sympa
Is the sympa user automatically created?

2017-09-28 09:02 UTC, SlothOfAnarchy commented on tasks/configure.yml
> +    src: edit_list.conf.j2
Where are the templates?

2017-09-30 14:02 UTC, dasJ commented on tasks/configure.yml
> +	src: sympa.conf.j2
*2 space

2017-09-30 14:02 UTC, dasJ commented on tasks/install.yml
> +  notify: restart sympa
And pleas capitalize the handler

2017-11-13 14:33 UTC, dasJ commented
Automatically bumping this issue because it was inactive for 46 days.

2017-11-14 17:22 UTC, closed without merging